---
- name: Create harness group
  ansible.builtin.group:
    name: "{{ oeb_studio_harness_group }}"
    system: true
    state: present
  become: true

- name: Create harness user
  ansible.builtin.user:
    name: "{{ oeb_studio_harness_user }}"
    group: "{{ oeb_studio_harness_group }}"
    system: true
    shell: /usr/sbin/nologin
    home: "{{ oeb_studio_harness_root }}"
    create_home: false
    state: present
  become: true

- name: Add harness user to docker group
  ansible.builtin.user:
    name: "{{ oeb_studio_harness_user }}"
    groups: docker
    append: true
  become: true
